#!/usr/bin/env sh

set -ex

docker buildx build --load -t tonistiigi/xx:dev --build-arg TEST_BASE_TYPE --build-arg TEST_BASE_IMAGE --build-arg TEST_WITH_DARWIN --build-arg SDKPLATFORM --build-arg SDKOS --target=dev ./base

if ! docker volume inspect xx-pkg-cache >/dev/null 2>&1; then
  docker volume create xx-pkg-cache >/dev/null 2>&1
fi

docker run -it --rm -v xx-pkg-cache:/pkg-cache tonistiigi/xx:dev
docker rmi tonistiigi/xx:dev
