#!/usr/bin/env sh

set -e

for l in $(xx-info env); do
  export $l
done

export GOOS=${TARGETOS}
export GOARCH=${TARGETARCH}

if [ "$TARGETARCH" = "arm" ]; then
  if [ ! -z "$TARGETVARIANT" ]; then
    case "$TARGETVARIANT" in
      "v5")
        export GOARM="5"
        ;;
      "v6")
        export GOARM="6"
        ;;
      *)
        export GOARM="7"
        ;;
    esac
  else
    export GOARM="7"
  fi
fi

if [ "$GOOS" = "wasi" ]; then
  export GOOS="js"
fi

if [ "$CGO_ENABLED" = "1" ]; then
  triple=$(xx-clang --print-target-triple || true)
  if [ -n "$triple" ]; then
    export CC=$triple-clang
    export CXX=$triple-clang++
  fi
fi

if [ -z "$GOBIN" ] && [ -n "$GOPATH" ] && [ -n "$GOARCH" ] && [ -n "$GOOS" ]; then
  export PATH=${GOPATH}/bin/${GOOS}_${GOARCH}:${PATH}
fi

exec go "$@"
