#!/usr/bin/env sh

set -e

# shellcheck source=./xx-common
. "$(command -v xx-common)"

flock_setup
if [ -z "$XX_DNF_NOLOCK" ]; then
  lock="/var/lock/xx-dnf"
  exec 9>$lock
  flock -x 9
  export XX_DNF_NOLOCK=1
fi

if [ -n "$XX_DEBUG_DNF" ]; then
  set -x
fi

unset XX_VENDOR # vendor for installing packages is always fedora

for l in $(xx-info env); do
  export "${l?}"
done

if [ "${TARGETOS}" != "linux" ]; then
  echo >&2 "skipping packages installation on ${XX_OS}"
  exit 0
fi

arg0="$(basename "$0")"
case $arg0 in
  xx-dnf) arg0="dnf" ;;
  xx-yum) arg0="yum" ;;
  xx-dnf5) arg0="dnf5" ;;
  xx-dnf4) arg0="dnf4" ;;
  xx-dnf-3) arg0="dnf-3" ;;
  xx-microdnf) arg0="microdnf" ;;
esac

if ! cmd_exists "$arg0"; then
  echo "Couldn't find '${arg0}', detecting dnf..."
  arg0="$(get_dnf)"
  echo "Found '${arg0}'"
fi

suffix=$XX_TRIPLE
if [ "$suffix" = "x86_64-linux-gnu" ]; then
  suffix="x86-64-linux-gnu"
fi
if [ "$XX_OS" = "windows" ]; then
  case "$XX_ARCH" in
    amd64) suffix="mingw-w64-x86-64" ;;
    386) suffix="mingw-w64-i686" ;;
    arm64) suffix="mingw-w64-aarch64" ;;
    arm) suffix="mingw-w64-arm" ;;
  esac
fi

setup() {
  if ! xx-info is-cross; then
    return
  fi
  done_file="/${XX_TRIPLE}/.xx-setup"
  if [ -f "$done_file" ]; then
    return
  fi
  yum_dir="/${XX_TRIPLE}/etc/yum.repos.d"
  mkdir -p "$yum_dir"

  cp -r /etc/yum.repos.d/* "$yum_dir/"

  . /etc/os-release
  basepkg=""
  case "${ID}" in
    fedora) basepkg="fedora-repos" ;;
    rhel) basepkg="subscription-manager coreutils findutils" ;;
    ol) basepkg="oraclelinux-release" ;;
    centos) basepkg="centos-release" ;;
    *) ;;
  esac
  $arg0 install -y --forcearch "$(xx-info rhel-arch)" --installroot "/${XX_TRIPLE}" --releasever "${VERSION_ID}" $basepkg

  touch "$done_file"
}

clean() {
  if ! xx-info is-cross; then
    return
  fi
  # safety first
  if [ -z "${XX_TRIPLE}" ]; then
    echo >&2 "invalid triple root $XX_TRIPLE"
    exit 1
  fi
  rm -rf "/${XX_TRIPLE:?}"
}

cmd() {
  setup
  root="/"
  if xx-info is-cross; then
    root="/${XX_TRIPLE}"
  fi
  n=$#
  iscompilerrt=
  isrustlib=
  for a in "$@"; do
    if [ $# = $n ]; then set --; fi
    case "$a" in
      "xx-c-essentials")
        set -- "$@" glibc-devel gcc
        ;;
      "xx-cxx-essentials")
        set -- "$@" gcc-c++
        ;;
      "compiler-rt" | "compiler-rt-static")
        iscompilerrt="$a"
        set -- "$@" "$a"
        ;;
      "rust-stdlib")
        set -- "$@" rust-std-static
        isrustlib=1
        ;;
      *)
        set -- "$@" "$a"
        ;;
    esac
  done
  if [ "$#" != "0" ]; then
    set -- "--installroot" "$root" "--forcearch" "$(xx-info rhel-arch)" "$@"
    echo "+ $arg0 " "$@"
  fi
  dnf "$@"
  if xx-info is-cross; then
    if [ -z "$XX_DNF_KEEP_BINARIES" ]; then
      rm -rf "/${XX_TRIPLE:?}/usr/bin/*"
    fi
    if [ -n "$iscompilerrt" ]; then
      for f in $($arg0 --installroot "$root" info -qL "$iscompilerrt" | grep 'clang_rt.'); do
        ff="/${f}"
        if [ ! -f "${ff}" ]; then
          mkdir -p "$(dirname "${ff}")"
          ln -s "/$(xx-info)/${f}" "${ff}"
        fi
      done
    fi
    # rust stdlib is accessed from the real root
    if [ -n "$isrustlib" ] && [ -d "$root/usr/lib/rustlib/$(xx-info)" ]; then
      ln -s "$root/usr/lib/rustlib/$(xx-info)" "/usr/lib/rustlib/$(xx-info)" || true
    fi
  fi
}

case "$1" in
  "setup")
    setup
    ;;
  "clean")
    clean
    ;;
  *)
    cmd "$@"
    ;;
esac
